// Generated by CoffeeScript 1.7.1
(function() {
  var join;

  join = function(S, L) {
    return L.reduce((function(A, x, i, l) {
      if (i === 0) {
        return x;
      } else {
        return A + S + x;
      }
    }), "");
  };

  window.join = join;

}).call(this);
