// Generated by CoffeeScript 1.7.1
(function() {
  var mapColors;

  mapColors = function(dotdata, fClrsUsers) {
    var dResult, data, uid;
    dResult = {};
    for (uid in dotdata) {
      data = dotdata[uid];
      dResult[uid] = fClrsUsers(uid);
    }
    return dResult;
  };

  window.mapColors = mapColors;

}).call(this);
