// Generated by CoffeeScript 1.7.1
(function() {
  var markUsers, updateVisVisible, userChecked;

  markUsers = function(T) {
    var bTurnOn, dUserGroups, uid, _i, _len, _ref, _results;
    dUserGroups = {
                      users: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],
                          masters: [10],  
                         phds: [2,4,7,11]
    };
    bTurnOn = d3.select('#chkGrp' + T).property('checked');
    _ref = dUserGroups[T.toLowerCase()];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      uid = _ref[_i];
      d3.select('#chkU' + uid).property('checked', bTurnOn);
      _results.push(updateVisVisible(uid));
    }
    return _results;
  };

  userChecked = function(uid) {
    return elem('chkU' + uid).checked;
  };

  updateVisVisible = function(uid) {
    var svg;
    svg = d3.select("#VIS");
    return svg.selectAll(".user" + uid).attr("visibility", function(d) {
      if (userChecked(d.user)) {
        return "visible";
      } else {
        return "hidden";
      }
    });
  };

  window.markUsers = markUsers;

  window.updateVisVisible = updateVisVisible;

  window.userChecked = userChecked;

}).call(this);


