// Generated by CoffeeScript 1.7.1
(function() {
  var userLines;

  userLines = function(userdata) {
    var entry, linedata, udat, uid, _i, _len, _ref;
    linedata = [];
    for (uid in userdata) {
      udat = userdata[uid];
      _ref = udat['lines'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entry = _ref[_i];
        entry.user = uid;
        linedata.push(entry);
      }
    }
    return linedata;
  };

  window.userLines = userLines;

}).call(this);
