// Generated by CoffeeScript 1.7.1
(function() {
  var userDots;

  userDots = function(userdata) {
    var dotdata, entry, i, newEntry, udat, uid, _ref;
    dotdata = [];
    for (uid in userdata) {
      udat = userdata[uid];
      console.log("dotprocess user " + uid);
      _ref = udat['DFs'];
      for (i in _ref) {
        entry = _ref[i];
        console.log(i + ".");
        newEntry = {};
        newEntry.user = uid;
        newEntry.x = entry[1][0];
        newEntry.y = entry[1][1];
        dotdata.push(newEntry);
      }
    }
    return dotdata;
  };

  window.userDots = userDots;

}).call(this);
